### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ashkeel** [wtfblub/Trashy#1]
Hello! I love this project and would love to build upon it but it currently has no license for me to do so! I'd love if you would add one!

Thank you!

**Comment by wtfblub** [comment]
There simply is no license, you are free to use this code however you want. No credits or anything required 👍

**Comment by ashkeel** [comment]
Oh thank you! However it would still be nice if you included a license so people don't have to ask you, as by not having a license you retain all copyright and give no permission to anyone.

If you wanna keep the humorous theme going, I'd suggest going for the [WTFPL](http://www.wtfpl.net/about/)!

**Comment by wtfblub** [comment]
> as by not having a license you retain all copyright and give no permission to anyone

Oh, I didn't know that. I'll add WTFPL then, thanks for the suggestion :)

**Comment by ashkeel** [comment]
Thank you so much for being so quick and kind about this! Cheers!
