### ISSUE TITLE
Items don't show up on Vtube Studio virtual webcam

### ISSUE THREAD

**Issue by rkatsushiro** [wtfblub/Trashy#2]
Hello! 

Mod works great, but I noticed something kind of major when playing around with it.

Basically the title; thrown objects don't seem to show up in OBS via the Vtube Studio virtual webcam. If there's just a setting I need to toggle for it to be viewable through the Vtube Studio virtual webcam, I haven't seen anything. I should also note I really only tested this using the "test" function in the mod off-stream, it's possible the mod behaves differently when actually streaming live.

Also pretty new to github; this is intended to be a throwaway account to bring this issue to light, and I'm not familiar with the normal protocol for this kind of thing. If there's anything in terms of recording, screenshots, logs, etc. that I need to include with this, please let me know

**Comment by wtfblub** [comment]
Thansk for the report, it should be working now 👍
