### ISSUE TITLE
Trashy icon randomly not appearing in vtube studio

### ISSUE THREAD

**Issue by GroggGorg** [wtfblub/Trashy#6]
Everything works perfectly when the icon appears, but randomly without any specific situation going on. upon running vtube studio sometimes the trashy logo simply does not appear and the rewards is unusable. Any tips?

**Comment by GroggGorg** [comment]
Sometimes I just close and open it again, but sometimes it takes numerous attempts, and its specially annoying when Im about to stream

**Comment by wtfblub** [comment]
Go to `VTube Studio\BepInEx\config` and open `BepInEx.cfg` in notepad. Search for `WriteUnityLog = false` and replace with `WriteUnityLog = true`, save file.
Now start Vtube Studio until the issue appears then close it and go to `VTube Studio\BepInEx` and send me the content of `LogOutput.log`

**Comment by GroggGorg** [comment]
Ok, Followed the steps, the logo didnt appear at first try, since yesterday is not coming back. This is the notepad I got:

[LogOutput.log](https://github.com/wtfblub/Trashy/files/8843822/LogOutput.log)

**Comment by wtfblub** [comment]
You have to have Steam open before starting VTube Studio but its preferred to start VTube Studio directly from Steam instead of using the shortcut or exe. Another alternative is to start it with `start_without_steam.bat` inside the VTube Studio folder

**Comment by GroggGorg** [comment]
For some reason, its 100% effective only by the start_without_steam.bat thing
Thanks a lot!!
